### ISSUE TITLE
[1.10.2] Slimey effect gene sample states: "Effect: *** ERROR ***"

### ISSUE THREAD

**Issue by RealGrep** [Lach01298/MoreBees#5] opened 2016-09-19 08:57 UTC
I suppose the subject line says most of it. Basically, I got to the Slimey bee, and I'm pulling genes with Gendustry. The gene sample for the Slimey effect shows, in the tooltip, "Effect: **\* ERROR ***" with everything after the colon in red.

I can tell it's the Slimey effect gene from the NBT data, which reads:
{species:"rootBees",chromosome:12,allele:"forestry.effectSlimey"} with 0 metadata.

This is with morebees-1.10.2-1.1.0.jar, forestry_1.10.2-5.2.9.247.jar, and gendustry-1.6.4.20-mc1.10.2.jar in Forge 2086.

**Comment by Lach01298** [comment] 2016-09-19 23:43
It was an error caused by me not registering my effects. strange thing is it crashed me looking at it not give me an error. well it should be fixed now with 1.1.3

**Closed as completed by Lach01298** 2016-09-19 23:43 UTC
Labels: bug

**Comment by RealGrep** [comment] 2016-09-20 11:45
Yay for me not crashing, I guess. Not crashing is good. :)

Thank you very much for the fix! I appreciate it.
